### ISSUE TITLE
h5页面套壳安卓ios，语音用不了

### ISSUE THREAD

**Issue by Mariah-feifei** [Zousdie/recorder#10]
发送不了语音
  startRecorder () {
      console.log('触摸开始1')
      let _this = this
      // _this.rc = new Recorderx(true)
      const AudioContext = window.AudioContext || window.webkitAudioContext
      _this.rc = new Recorderx(AudioContext, {recordable: true})
      _this.$nextTick(() => {
        _this.rc.start()
          .then(() => {
            console.log('start recording')
            _this.recorder = true
          }).catch(error => {
            console.log('Recording failed.', error)
            Toast.fail('此设备不支持')
          })
      })
    },

在谷歌火狐浏览器走了then（）但是打包apk后测试就一直走 catch()  不知道问题出在哪  能否帮忙看一下

**Comment by Zousdie** [comment]
这个问题有可能是兼容性导致的，请先检查你的app的 webview 是否支持录音的API，你可以在app中嵌入这个页面来做检查：`https://zousdie.github.io/recorderx/`

**Comment by Mariah-feifei** [comment]
加了中间页，点击start报：Recording failed. NotReadableError: Could not start audio source。这是不支持API 吗？ios和安卓都不可以，是不是用不了了，有办法解决吗？

**Comment by Zousdie** [comment]
你可以搜索一下这个错误相关的信息，app嵌入页面我不是很懂，但基本可以排除库本身bug的可能了。

p.s. 由于webview的一些限制，hybrid app要实现录音一般是通过协议调用原生api实现，你不妨换个思路？
