### ISSUE TITLE
引入项目，遇到问题了

### ISSUE THREAD

**Issue by xmhuangliumei** [Zousdie/recorder#2]
按照你这边的提示，编码到vue项目中，一直报错，希望能得到你的帮助！Error in v-on handler: "TypeError: Cannot read property 'getAudioTracks' of undefined"

**Comment by xmhuangliumei** [comment]
按照你这边的提示，编码到vue项目中，一直报错，希望能得到你的帮助！Error in v-on handler: "TypeError: Cannot read property 'getAudioTracks' of undefined"  ，方便的话，我在微信上联系您哈，感谢帮助

**Comment by Zousdie** [comment]
@xmhuangliumei

可以给出更多的代码示例并说明你的浏览器环境么？

这个错误看起来像是在执行**暂停**时触发的。

pause 函数源码：
```
pause () {
    this[state] = RECORDER_STATE.READY;
    this.recorder.disconnect();
    this.stream.getAudioTracks()[0].stop();
}
```

需要更多的示例以便排查错误

**Comment by Zousdie** [comment]
@xmhuangliumei 

您是否在调用 `start` 函数开始录音前便调用了 `pause` 函数？
在 `start` 函数执行前，`Recorderx` 实例上的 `stream` 属性是 `undefined`, 所以会引发错误。
