### ISSUE TITLE
录入的原始pcm声音出现了变声(变慢变粗)

### ISSUE THREAD

**Issue by mazhihong** [Zousdie/recorder#3]
环境：
Mac OS 10.11.6
Google Chrome 
版本 73.0.3683.103（正式版本） （64 位）

rc = new Recorderx({
                recordable: true,
                sampleRate: 16000,
                sampleBits: 16,
                bufferSize: 8192,
                numberOfInputChannels: 1,
                numberOfOutputChannels: 1
              });

另外：通过npm安装，package.js 中 "main": "dist/index.js", dist目录下上没有index.js这个文件的，会报not found module，目前上通过recorderx.min.js拷贝为index.js 解决的。

**Comment by Zousdie** [comment]
@mazhihong 
npm 安装问题：上个版本在更新 `rollup` 构建配置后 `package.js` 的 `main` 字段没有更新，这个问题很快会在下个 PR 修复。
**变慢变粗**的问题我还需要进一步排查，因为在 Windows 的 Chrome 73，Edge 18, Firefox 65 下都没有出现

**Comment by mazhihong** [comment]
我也是在Mac OS下测试有问题，项目中的demo测试也是一样。windows测试都是没有问题的。
但是用别的项目的js录音就没有问题，所以排除是设备的问题。

**Comment by Zousdie** [comment]
@mazhihong recorderx 已发布 2.0.0，可以试试看

关于MAC上录音变慢变粗的原因（我手边没有可供调试的 MAC）：

1. 可能是压缩算法导致的
2. 在线 Demo 中是边录音边播放，如果没有使用耳麦录音则会导致破音

**Comment by mazhihong** [comment]
我试了一下2.0.0中的demo声音是正常的。但是我把2.0.0引入到我的typescript项目中，报错
'Recorderx' only refers to a type, but is being used as a value here.ts(2693)

import {default as Recorderx} from 'recorderx';
const  rc = new Recorderx();  //这行报错

**Comment by Zousdie** [comment]
@mazhihong 这个问题已经迁移到 #7
