### ISSUE TITLE
得到的音频数据好像有问题，帮忙看看

### ISSUE THREAD

**Issue by xmhuangliumei** [Zousdie/recorder#5]
1.recordeFuc() {
      console.log("开始录音");
     
      rc = new Recorderx({
        recordable: true,
        sampleRate: 16000,
        sampleBits: 16,
        bufferSize: 8192,
        numberOfInputChannels: 1,
        numberOfOutputChannels: 1
      });
      
      rc.start();
    },
2.handleRecordStop() {
      console.log("松开发送");
     
      //获取pcm录音
      var pcm = rc.getRecord();
      console.log('666',pcm);
        //如果要获取blob对象（二进制）
      // const blob = encodeWAV(pcm, 16, 44100);这个方法一直提示找不到，在前面已经从recorderx.min.js引用过来
   
       //暂停录音
      rc.pause();

    },

3.得到的音频输出数据是：
Float32Array(81920) [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …]，这个数据上传到科大讯飞上，解析不出文字

**Comment by Zousdie** [comment]
@xmhuangliumei 你是通过npm安装的么？还是直接引入的scirpt

**Comment by Zousdie** [comment]
有朋友反应，在 mac 上录音会失真、变慢，但在 Windows 上却正常，正在解决这个问题。
目前的导出方法不够直观，导出 pcm 数据确实有一些问题，在这之前你可以先试试导出 wav 格式

**Comment by Zousdie** [comment]
@xmhuangliumei 已发布2.0.0，相关 API 有更新，可以参考中文文档

新版本下支持导出原始的 RAW 数据、PCM 和 WAV，均支持启用/禁用数据压缩，PCM 数据是 ArrayBuffer 类型，RAW 数据是没有做其他处理（支持抽点压缩）的原始的 Float32Array
