### ISSUE TITLE
Type declaration error

### ISSUE THREAD

**Issue by Zousdie** [Zousdie/recorder#7]
Recorderx type declaration is incorrect.

error: `'Recorderx' only refers to a type, but is being used as a value here.ts(2693)`

**Comment by mazhihong** [comment]
升级到2.0.1后，没有报这个错误了。
但是我的项目build不出来js，也没有任何明显的报错，我怀疑是冲突了，删除node_modules重新build也不行。
测试发现 1.0.3也是这个问题，只有1.0.2是可以的。


如下是我的package.json
{
  "name": "xxx",
  "version": "1.0.0",
  "description": "xxx",
  "main": "./dist/index.html",
  "scripts": {
    "dev": "gulp --debug",
    "prod": "gulp",
    "lib": "gulp lib"
  },
  "repository": {
    "type": "git",
    "url": "git@xxx/eu-core.git"
  },
  "author": "xxx",
  "license": "ISC",
  "dependencies": {
    "@babel/runtime": "^7.4.4",
    "@types/pako": "^1.0.0",
    "@types/pixi.js": "^4.7.3",
    "eventemitter3": "^3.1.0",
    "lodash": "^4.17.10",
    "pako": "^1.0.6",
    "pixi.js": "^4.7.3",
    "recorderx": "^1.0.2",
    "tern": "^0.23.0",
    "vconsole": "^3.2.0",
    "yargs": "^12.0.2"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es3": "^1.0.1",
    "babelify": "^8.0.0",
    "browserify": "^16.2.0",
    "gulp": "^3.9.1",
    "gulp-clean": "^0.4.0",
    "gulp-merge": "^0.1.1",
    "gulp-sequence": "^1.0.0",
    "gulp-sourcemaps": "^2.6.4",
    "gulp-typescript": "^4.0.2",
    "gulp-uglify": "^3.0.0",
    "gulp-util": "^3.0.8",
    "gulp-webserver": "^0.9.1",
    "merge-stream": "^1.0.1",
    "run-sequence": "^2.2.1",
    "tsify": "^4.0.0",
    "typescript": "^2.8.3",
    "vinyl-buffer": "^1.0.1",
    "vinyl-source-stream": "^2.0.0",
    "watchify": "^3.11.0"
  }
}

**Comment by Zousdie** [comment]
@mazhihong 我测试了使用 webpack 和 rollup 进行构建，没有出现这个问题。
我发现你的项目中使用了 babel6 和 browserify，我不清楚这有没有关系
或者检查一下 gulp 构建脚本？

**Comment by Zousdie** [comment]
我测试了使用 webpack 和 rollup 进行构建，一切正常。
或者检查一下 gulp 构建脚本？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 马志宏 <notifications@github.com>
发送时间: Saturday, April 27, 2019 12:00:18 PM
收件人: Zousdie/recorderx
抄送: Jialiang T.; State change
主题: Re: [Zousdie/recorderx] Type declaration error (#7)


升级到2.0.1后，没有报这个错误了。
但是我的项目build不出来js，也没有任何明显的报错，我怀疑是冲突了，删除node_modules重新build也不行。
测试发现 1.0.3也是这个问题，只有1.0.2是可以的。

如下是我的package.json
{
"name": "xxx",
"version": "1.0.0",
"description": "xxx",
"main": "./dist/index.html",
"scripts": {
"dev": "gulp --debug",
"prod": "gulp",
"lib": "gulp lib"
},
"repository": {
"type": "git",
"url": "git@xxx/eu-core.git"
},
"author": "xxx",
"license": "ISC",
"dependencies": {
"@babel/runtime": "^7.4.4",
"@types/pako": "^1.0.0",
"@types/pixi.js": "^4.7.3",
"eventemitter3": "^3.1.0",
"lodash": "^4.17.10",
"pako": "^1.0.6",
"pixi.js": "^4.7.3",
"recorderx": "^1.0.2",
"tern": "^0.23.0",
"vconsole": "^3.2.0",
"yargs": "^12.0.2"
},
"devDependencies": {
"babel-core": "^6.26.3",
"babel-preset-es2015": "^6.24.1",
"babel-preset-es3": "^1.0.1",
"babelify": "^8.0.0",
"browserify": "^16.2.0",
"gulp": "^3.9.1",
"gulp-clean": "^0.4.0",
"gulp-merge": "^0.1.1",
"gulp-sequence": "^1.0.0",
"gulp-sourcemaps": "^2.6.4",
"gulp-typescript": "^4.0.2",
"gulp-uglify": "^3.0.0",
"gulp-util": "^3.0.8",
"gulp-webserver": "^0.9.1",
"merge-stream": "^1.0.1",
"run-sequence": "^2.2.1",
"tsify": "^4.0.0",
"typescript": "^2.8.3",
"vinyl-buffer": "^1.0.1",
"vinyl-source-stream": "^2.0.0",
"watchify": "^3.11.0"
}
}

―
